<?php

/**
 * @file
 * Slider install file
 */

/**
 * Implements hook_node_info()
 */
function slider_node_info() {
    return array(
        'slider' => array(
            'name' => t('Slider'),
            'base' => 'slider',
            'description' => t('You can define your slider content here.'),
            'has_title' => TRUE,
            'title_label' => t('Slider')
        )
    );
}

/**
 * Implement hook_form()
 */
function slider_form($node, $form_state) {
    return node_content_form($node, $form_state);
}

/**
 * Implements hook_form_alter().
 * This is remove the promote to frontpage, and make sticky options from node edit pages
 */
function slider_form_alter(&$form, &$form_state, $form_id) {
    if ('slider_node_form' == $form_id) {
        unset($form['options']['sticky']);
        unset($form['options']['promote']);
        unset($form['revision_information']);
        unset($form['comment_settings']);
        unset($form['menu']);
        unset($form['author']);
        unset($form['path']);
    }
}